# Generated by Django 5.1.6 on 2025-02-19 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the service', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description of this service', null=True)),
                ('estimated_time', models.DurationField(help_text='Estimated completion time (hh:mm:ss)')),
                ('active', models.BooleanField(default=True, help_text='Indicates if the service is currently active/available')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the service category', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the category', null=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DetailedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('printer', 'Printer')], help_text='Device undergoing repair or receiving the service (e.g., Laptop, Smartphone)', max_length=100)),
                ('changes_to_make', models.TextField(help_text='Description of the repair or change involved in this service e.g.: Adding RAM, Replacing screen. should begin with a verb')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the detailed service in KES', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Additional information about a detailed service', null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='services.service')),
            ],
            options={
                'verbose_name': 'Detailed Service',
                'verbose_name_plural': 'Detailed Services',
                'ordering': ['service', 'device'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(help_text='Category of the service', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory'),
        ),
        migrations.CreateModel(
            name='ServicePartsRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('mandatory', models.BooleanField(default=True)),
                ('detailed_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.detailedservice')),
                ('part_type', models.ManyToManyField(help_text='Part(s) required for this service', related_name='service_parts_required', to='inventory.devicepart')),
            ],
            options={
                'verbose_name': 'Service Part Required',
                'verbose_name_plural': 'Service Parts Required',
                'ordering': ['detailed_service', 'part_type__name'],
            },
        ),
    ]
