# Generated by Django 5.1.6 on 2025-02-19 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('printer', 'Printer')], default='laptop', max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('repair_status', models.CharField(blank=True, choices=[('completed', 'Completed'), ('returned', 'Returned'), ('in_progress', 'In Progress')], default='in_progress', max_length=20, null=True)),
                ('sale_status', models.CharField(blank=True, choices=[('new', 'New'), ('sold', 'Sold'), ('refurbished', 'Refurbished')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DevicePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the part e.g.: 16GB DDR4 RAM, 256GB NVMe SSD, or even the accompanying bag', max_length=100)),
                ('model', models.CharField(help_text='Model number or Brand of the part', max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Number of parts in stock or those which came with the device', null=True)),
                ('status', models.CharField(blank=True, choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('used', 'Used'), ('defective', 'Defective'), ('disposed', 'Disposed')], max_length=20, null=True)),
                ('warranty_months', models.PositiveIntegerField(default=0)),
                ('minimum_stock', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_laptop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='inventory.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceRepairHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('repair_date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device')),
                ('parts_replaced', models.ManyToManyField(to='inventory.devicepart')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PartMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('repair', 'Used in Repair'), ('sale', 'Used in a Sale')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.devicepart')),
            ],
        ),
    ]
