# Generated by Django 5.1.6 on 2025-02-19 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0001_initial'),
        ('inventory', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='detailed_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.detailedservice'),
        ),
        migrations.AddField(
            model_name='booking',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.device'),
        ),
        migrations.AddField(
            model_name='booking',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='accounts.staffprofile'),
        ),
        migrations.AddField(
            model_name='bookingparts',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingparts',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.devicepart'),
        ),
        migrations.AddField(
            model_name='booking',
            name='parts_used',
            field=models.ManyToManyField(through='bookings.BookingParts', to='inventory.devicepart'),
        ),
    ]
